# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
stripe_api_key: sk_test_51Jtvd7JVOcjoetwAMriQzWqNlcVfvRjxTswrstbuvNZps2JIEMT6KUrctm8GeEJ8kgJwzX5dcfc4ITITRjPjp2iT00EwpRIXoU
stripe_publishable_key: pk_test_51Jtvd7JVOcjoetwAq93su8WVXAs9vOTqYKYuKJNYvtPUIO9ANZHhfO7lucD31vrmBJp0lk9MoybwqMDqh98yNqXN00Krz3aRC5
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
